---
# tasks file for tailscale

- name: add tailscale apt signing keys
  apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.gpg
    state: present

- name: add tailscale ppa
  apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main
    state: present

- name: installing tailscale
  become: yes
  apt:
    pkg:
      - tailscale
    state: present
